FROM ubuntu
RUN apt-get update
RUN apt-get install nginx -y
COPY index.html /var/www/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


# keyword argument
# gives comments
# Always starts with Fromkeyword

#FROM ubuntu
#ENV dirName myroot
#ENV user1 username
#RUN mkdir "$myroot"
#RUN useradd $user1
#COPY hostpath/filename /containerdirectory
#ADD myfiles.tar /contdir
#CMD ["/bin/bash"]
#ENTRYPOINT ["entrypoint.sh"]

